[build]
  publish = "dist"
  command = "npm run build:ci"
  functions = "functions"

[build.environment]
  ELEVENTY_ENV = "prod"

[build.processing]
  skip_processing = true

[[headers]]

 for = "/*"
 [headers.values]
   X-Frame-Options = "DENY"
   X-Content-Type-Options = "nosniff"
   Referrer-Policy= "strict-origin-when-cross-origin"
   Content-Security-Policy = "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'; frame-ancestors 'none';"
