[build]
  publish = "dist"
  command = "npm run build"
  functions = "functions"


[build.processing]
  # we will optimise css and js in our build
  skip_processing = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  # compress = true

[[headers]]

 for = "/*"
 [headers.values]
   X-Frame-Options = "DENY"
   X-XSS-Protection = "1; mode=block"
   X-Content-Type-Options = "nosniff"
   Referrer-Policy= "strict-origin-when-cross-origin"
